### ISSUE TITLE
FSA9480 usb switch

### ISSUE THREAD

**Issue by PabloPL** [PabloPL/linux#16]
There is already driver at https://github.com/tom3q/linux/commit/c54d9ad07eb30dc0ae11f4e13d0cbd0c11c77f03
It needs to be updated to new extcon api (work done on for-upstream/fsa9480).

**Comment by PabloPL** [comment]
extcon: fsa9480: Adjust for new extcon interface
extcon: fsa9480: Add manual switching sysfs

**Comment by PabloPL** [comment]
TODO:
- max8998 charger should listen for extcon change and enable/disable charging
- max17040 battery should listen for charger/extcon and show correct state (discharging/not charging/charging/etc)

**Comment by PabloPL** [comment]
fsa9480 got accepted in mainline

**Comment by xc-racer99** [comment]
For reference, a charger-manager DTS is available at https://git.tizen.org/cgit/platform/kernel/linux-exynos/commit/arch/arm/boot/dts/exynos3250-rinato.dts?h=dev/rebase_v4.1.51&id=b16ec86de799d4300359dd9881df00c8f03a4665

However, there needs to be a bunch of work on it, including adding the charger regulator to max8998 and adjusting the extcon interface to actually work...
