### ISSUE TITLE
Aries v2 patches

### ISSUE THREAD

**Issue by PabloPL** [PabloPL/linux#17]
Branch: for-upstream/aries-patches-v2

Here is list of patches which will be submited in v2 patchset for aries.
- [x] s5p-jpeg
- [x] s5p-mfc
- [x] poweroff
- [x] vibrator
- [x] atmel_mxt_ts
- [x] bluetooth

**Comment by MYEUHD** [comment]
Enabling G2D only requires defconfig changes.
In theory, it should be just
`CONFIG_VIDEO_SAMSUNG_S5P_G2D=m`
Can you test it please? My memory card got damaged and I didn't get a new one yet.

**Comment by PabloPL** [comment]
I talked about g2d on exynos irc.
There are 2 g2d modules - one is inside drivers/media/platform/s5p-g2d (old but supporting s5pv210) and second is inside drivers/gpu/drm/exynos (much newer, but don't support s5pv210 :( ).
I don't know if anything is using g2d from media (walyand could/is using driver from drm).

**Comment by xc-racer99** [comment]
RE: G2D - there was a patchset with some more info on the DRM G2D driver at https://lore.kernel.org/patchwork/patch/680927/

**Comment by PabloPL** [comment]
For G2D i've created separate issue https://github.com/PabloPL/linux/issues/18, so let's move all discusion there.
@xc-racer99 I've created https://github.com/xc-racer99/u-boot-galaxys4g/issues/11
Adding more logs from pc.

**Comment by PabloPL** [comment]
@xc-racer99  Could You check if touchscreen is working fine for You ? I've set it to pull_none and irq edge failing. For me it's working fine.

**Comment by xc-racer99** [comment]
Yep, works fine for me.

**Comment by PabloPL** [comment]
Patches accepted and merged into mainline.

**Comment by MYEUHD** [comment]
Note that we don't actually need that much reserved memory for MFC.
In fact, it has been reduced to 35MiB in Android Kernels since 2012 and it has been working fine.
https://github.com/CyanogenMod/android_kernel_samsung_aries/commit/164a90a7cd4f7ed363a5b8e74d466186912d05a7

**Comment by PabloPL** [comment]
@MYEUHD I took values from original kernel (released by samsung for i9000 or nexus s for google).
We can look later at decrasing it, now we focus on adding support for as much things as possible.
