### ISSUE TITLE
I porting mainline kernel found common clock framework is not work

### ISSUE THREAD

**Issue by LazyCat-xiao** [PabloPL/linux#46]
i can boot kernel 5.7 in my board and 5.8 or high is not boot. in 5.7 fimd is not have sclk_fimd.

**Comment by xc-racer99** [comment]
Interesting, what board is this on?  I haven't had an issue with mainline v5.9-v5.10 while bisecting the display issues a week ago.  I was using galaxys (i9000).

**Comment by LazyCat-xiao** [comment]
my board is similar as smdkv210, i use 5.10 only have uart and i cant entry console. and 5.7 i fonud the clock system is not init. the pll value is not set, i set 400mhz in uboot and kernel is running on 400mhz. and more sclk is zero. the sclk_uart and sclk_mmc not zero is init in uboot.

**Comment by xc-racer99** [comment]
What u-boot are you using?  Are you using a vendor u-boot or my fork (from https://github.com/xc-racer99/u-boot-aries/) and what is your initial boot loader?

For your linux kernel, are you using my repo, mainline, or something else (if so, is it uploaded somewhere)?

**Comment by LazyCat-xiao** [comment]
sorry, my english is bad. but i want run kernel in 5.x to learn. it can run on 2.6 and 3.0 but now 5.11-rc. 
i use uboot in my repo ( https://github.com/LazyCat-xiao/x210-uboot202010/) and it is my bl2. uboot flash in my sd card. the kernel is 5.7.19 in mainline (i download in https://mirrors.tuna.tsinghua.edu.cn/kernel/). i look for the pll value in linux-5.7.19/driver/clk/samsung/clk-s5pv210.c, but i cant found any. it can work but not good.

**Comment by LazyCat-xiao** [comment]
i use RGB-LCD need set FIMD clock in UBOOT. when i not set in UBOOT it cant work. More peripherals clock is zero.

**Comment by MateuszKrawczuk** [comment]
Could you share with me the vendor Linux kernel which is working with your board? I will look into the issue, but probably you need to change the value for in your board device tree. I would recommend check values set for: 
	xxti: oscillator-0 {
		compatible = "fixed-clock";
		clock-frequency = <0>;
		clock-output-names = "xxti";
		#clock-cells = <0>;
	};

	xusbxti: oscillator-1 {
		compatible = "fixed-clock";
		clock-frequency = <0>;
		clock-output-names = "xusbxti";
		#clock-cells = <0>;
	};

**Comment by LazyCat-xiao** [comment]
in s5pv210.dsi xxti is 0, and i add xxti 24MHz in my dts more peripherals clock is not 0. thanks
