### ISSUE TITLE
exynos7580 - j7elte device request

### ISSUE THREAD

**Issue by Kabir404** [PabloPL/linux#49]
Hello there!

I hope you're having a good day. So it would be nice if you could actually improve on exynos7580 and actually add support for the Samsung Galaxy J7 from 2015 which is codenamed j7elte.

I just ported that device to run PostMarketOS based on the downstream LinageOS kernel and am trying to run your kernel on it
[Here is my device port for more information...](https://wiki.postmarketos.org/wiki/Samsung_Galaxy_J7_(samsung-j7elte))

**Comment by PabloPL** [comment]
Sorry i don't have such device (A3 2016) anymore. Also with current state (my branches for 7580) it was just booting with serial console, nothing else was working yet.
