### ISSUE TITLE
Submit atmel_mxt_ts patches

### ISSUE THREAD

**Issue by PabloPL** [PabloPL/linux#6]
Patches submited to mainline, waiting for feedback.

After merge, two patches adding it to aries can submited with other (vibrator/audio/lcd/etc).

**Comment by PabloPL** [comment]
It looks like no patches are required to make touchscreen working (need to replace regulators with reset gpio), but created patches were still submited to upstream.

**Comment by xc-racer99** [comment]
Can this be closed now that Aries v2 was accepted upstream?

**Comment by PabloPL** [comment]
It turns out aries didn't needed any from thouse patches. I would like to have it open because patches which i've created i want to push to mainline (to not waste them).
