### ISSUE TITLE
Submit s6e63m0 panel driver

### ISSUE THREAD

**Issue by PabloPL** [PabloPL/linux#7]
Changes on **for-upstream/s6e63m0-panel**

**Comment by PabloPL** [comment]
@xc-racer99 I saw that You had panel driver for galaxys4g. Is it working?
On branch aries-panel i also have working panel driver, but it looks like Your have more functionalities (possible to change gamma table).

**Comment by xc-racer99** [comment]
I didn't test it very much but yes, it was working.  It's basically the old mainline s6e63m0 driver hacked together for the drm panel interfaces - it would need a fair bit of cleanup.  It had the three gamma tables that you could switch between with a sysfs entry

**Comment by PabloPL** [comment]
I hope that we'll be able to use it in uboot. There is uboot menu config available.
In this way we could have multiboot like menu (for example ums/boot from onenand/boot from mmc/boot from sdcard)

**Comment by PabloPL** [comment]
Driver created and send to mainline.

TODO submit change in s5pv210-aries.dtsi and s5pv210_defconfig

**Comment by xc-racer99** [comment]
What was the trick for brightness?

**Comment by PabloPL** [comment]
@xc-racer99 
If You look at function **s6e63m0_dcs_write**, this will send first u8 value as command and rest will be send as data (by doing *data | 0x100 in loop).
So in any place where we use it we should be using it in this way
```
// 
s6e63m0_dcs_write_seq_static(ctx, MCS_GAMMA_CTRL, 0x01);
// this will call s6e63m0_dcs_write_seq_static with param data = [MCS_GAMMA_CTRL, 0x01]
// so at end s6e63m0_dcs_write_seq_static will send
// COMMAND = MCS_GAMMA_CTRL
// DATA = 0x01 (or anything remaining)
```

My problem (mistake) with setting gamma was that i was trying to do this in following way
```
s6e63m0_dcs_write_seq_static(ctx, MCS_GAMMA_CTRL, 0x01);
s6e63m0_dcs_write(ctx, s6e63m0_gamma_22[ctx->brightness], ARRAY_SIZE(s6e63m0_gamma_22[ctx->brightness]) );
s6e63m0_dcs_write_seq_static(ctx, MCS_GAMMA_CTRL, 0x01);

```
So it was treating first value of s6e63m0_gamma_22 as command, where i should (how i'm doing it now)
```
s6e63m0_dcs_write(ctx,s6e63m0_gamma_22[ctx->brightness], ARRAY_SIZE(s6e63m0_gamma_22[ctx->brightness]));
s6e63m0_dcs_write_seq_static(ctx, MCS_GAMMA_CTRL, 0x01);
```
With 
```
MCS_GAMMA_CTRL, 0x01
```
added to all gamma levels in all gamma tables, so now they look like this

```
static u8 const s6e63m0_gamma_22[MAX_GAMMA_LEVEL][GAMMA_TABLE_COUNT] = {
	{ MCS_GAMMA_CTRL, 0x00,
	  0x18, 0x08, 0x24, 0x78, 0xEC, 0x3D, 0xC8,
	  0xC2, 0xB6, 0xC4, 0xC7, 0xB6, 0xD5, 0xD7,
	  0xCC, 0x00, 0x39, 0x00, 0x36, 0x00, 0x51 },
```

**Comment by PabloPL** [comment]
The same thing is done in panel-samsung-ld9040 (compare gamma values with removed driver https://patchwork.kernel.org/patch/10585185/).

**Comment by xc-racer99** [comment]
Found another user who may have the s6e63m0 panel, see https://gitlab.com/postmarketOS/pmaports/merge_requests/195/diffs

**Comment by PabloPL** [comment]
I wonder if he/she knows about mainline support.

**Comment by xc-racer99** [comment]
I've left a comment there, they tested your mainline driver, but screen appears rotated 180 degrees.  Apparently stock driver writes a slightly different sequence in it.

**Comment by PabloPL** [comment]
Or maybe it's just mounted in different way. Didn't saw any, but there should be some generic way to rotate display.

**Comment by xc-racer99** [comment]
Funny enough, I can't find any generic way to rotate a display.  Closest I've found is rotate-display in the xilinx driver.

The difference is at https://github.com/PabloPL/linux/blob/for-upstream/s6e63m0-panel/drivers/gpu/drm/panel/panel-samsung-s6e63m0.c#L202 where the sequence is 0x0, 0x0, 0x0

**Comment by PabloPL** [comment]
Hm, i could do some testing, maybe it would be just a matter of adding one parameter (rotation) to it.
Will check it later.

**Comment by PabloPL** [comment]
Driver accepted in mainline (but not yet in next/stable).

**Comment by PabloPL** [comment]
Device tree fixes will be merged as part of https://github.com/PabloPL/linux/issues/27
