### ISSUE TITLE
Submit touchkey driver

### ISSUE THREAD

**Issue by PabloPL** [PabloPL/linux#8]

**Comment by xc-racer99** [comment]
@fourkbomb
What's the status of https://github.com/fourkbomb/linux/commit/524442d47c88d5c25a167eaae65aaa0ad31df051 with regards to mainline?  I'm using it as a stepping stone to add support for aries (first-gen Galaxy S devices).  Thanks!

@PabloPL Would you mind testing https://github.com/PabloPL/linux/commits/for-upstream/touchkey on the i9000?  It's working to my satisfaction here.

**Comment by PabloPL** [comment]
Works fine for me (after adding CONFIG_REGULATOR_FIXED_VOLTAGE and CONFIG_KEYBOARD_TM2_TOUCHKEY).

You can add my "Tested-by" (like it's done for example https://patchwork.kernel.org/patch/10354345/)

**Comment by fourkbomb** [comment]
Feel free to submit it upstream (and CC me). I doubt I'll get a chance to do it myself in the near future.

**Comment by PabloPL** [comment]
Patches fixed (there needs to be separate patches for adding documentation and making changes in driver - it shouldn't be in one patch), added missing comments etc and send to upstream for review.

**Comment by PabloPL** [comment]
@fourkbomb Do You accept dropping name from touchkey_variant struct (like it was mentioned in mailing list)? I could make this change, since i want to submit new version upstream.

**Comment by PabloPL** [comment]
Accepted in mainline.
